{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.10.14","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kaggle":{"accelerator":"tpu1vmV38","dataSources":[],"dockerImageVersionId":30748,"isInternetEnabled":true,"language":"python","sourceType":"notebook","isGpuEnabled":false}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"code","source":"!pip install --upgrade transformers","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","execution":{"iopub.status.busy":"2024-08-21T17:12:02.560610Z","iopub.execute_input":"2024-08-21T17:12:02.561152Z","iopub.status.idle":"2024-08-21T17:12:18.565967Z","shell.execute_reply.started":"2024-08-21T17:12:02.561123Z","shell.execute_reply":"2024-08-21T17:12:18.565213Z"},"trusted":true},"execution_count":1,"outputs":[{"name":"stdout","text":"Requirement already satisfied: transformers in /usr/local/lib/python3.10/site-packages (4.42.3)\nCollecting transformers\n  Downloading transformers-4.44.1-py3-none-any.whl (9.5 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m9.5/9.5 MB\u001b[0m \u001b[31m51.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n\u001b[?25hRequirement already satisfied: filelock in /usr/local/lib/python3.10/site-packages (from transformers) (3.15.4)\nRequirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/site-packages (from transformers) (6.0.1)\nRequirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/site-packages (from transformers) (4.66.4)\nRequirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/site-packages (from transformers) (2024.5.15)\nRequirement already satisfied: requests in /usr/local/lib/python3.10/site-packages (from transformers) (2.32.3)\nRequirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.10/site-packages (from transformers) (0.23.4)\nRequirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/site-packages (from transformers) (24.1)\nRequirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/site-packages (from transformers) (0.4.3)\nRequirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/site-packages (from transformers) (0.19.1)\nRequirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/site-packages (from transformers) (1.26.4)\nRequirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (2024.6.1)\nRequirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.12.2)\nRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests->transformers) (2024.7.4)\nRequirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests->transformers) (3.7)\nRequirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/site-packages (from requests->transformers) (3.3.2)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests->transformers) (2.2.2)\nInstalling collected packages: transformers\n  Attempting uninstall: transformers\n    Found existing installation: transformers 4.42.3\n    Uninstalling transformers-4.42.3:\n      Successfully uninstalled transformers-4.42.3\nSuccessfully installed transformers-4.44.1\n\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n\u001b[0m\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m23.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.2\u001b[0m\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n","output_type":"stream"}]},{"cell_type":"code","source":"!pip install datasets","metadata":{"execution":{"iopub.status.busy":"2024-08-21T17:12:18.567582Z","iopub.execute_input":"2024-08-21T17:12:18.567840Z","iopub.status.idle":"2024-08-21T17:12:25.792487Z","shell.execute_reply.started":"2024-08-21T17:12:18.567814Z","shell.execute_reply":"2024-08-21T17:12:25.791587Z"},"trusted":true},"execution_count":2,"outputs":[{"name":"stdout","text":"Collecting datasets\n  Downloading datasets-2.21.0-py3-none-any.whl (527 kB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m527.3/527.3 kB\u001b[0m \u001b[31m8.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n\u001b[?25hRequirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/site-packages (from datasets) (1.26.4)\nRequirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.10/site-packages (from datasets) (0.3.8)\nCollecting multiprocess\n  Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m134.8/134.8 kB\u001b[0m \u001b[31m12.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hRequirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.10/site-packages (from datasets) (2.32.3)\nRequirement already satisfied: pandas in /usr/local/lib/python3.10/site-packages (from datasets) (2.2.2)\nCollecting xxhash\n  Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m194.1/194.1 kB\u001b[0m \u001b[31m15.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hRequirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.10/site-packages (from datasets) (4.66.4)\nRequirement already satisfied: packaging in /usr/local/lib/python3.10/site-packages (from datasets) (24.1)\nRequirement already satisfied: filelock in /usr/local/lib/python3.10/site-packages (from datasets) (3.15.4)\nRequirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/site-packages (from datasets) (16.1.0)\nRequirement already satisfied: huggingface-hub>=0.21.2 in /usr/local/lib/python3.10/site-packages (from datasets) (0.23.4)\nRequirement already satisfied: fsspec[http]<=2024.6.1,>=2023.1.0 in /usr/local/lib/python3.10/site-packages (from datasets) (2024.6.1)\nRequirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/site-packages (from datasets) (6.0.1)\nCollecting aiohttp\n  Downloading aiohttp-3.10.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.2/1.2 MB\u001b[0m \u001b[31m34.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m\n\u001b[?25hCollecting aiohappyeyeballs>=2.3.0\n  Downloading aiohappyeyeballs-2.4.0-py3-none-any.whl (12 kB)\nCollecting frozenlist>=1.1.1\n  Downloading frozenlist-1.4.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (239 kB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m239.5/239.5 kB\u001b[0m \u001b[31m18.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hCollecting async-timeout<5.0,>=4.0\n  Downloading async_timeout-4.0.3-py3-none-any.whl (5.7 kB)\nRequirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/site-packages (from aiohttp->datasets) (23.2.0)\nCollecting multidict<7.0,>=4.5\n  Downloading multidict-6.0.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (124 kB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m124.3/124.3 kB\u001b[0m \u001b[31m9.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hCollecting yarl<2.0,>=1.0\n  Downloading yarl-1.9.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (301 kB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m301.6/301.6 kB\u001b[0m \u001b[31m21.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hCollecting aiosignal>=1.1.2\n  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)\nRequirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/site-packages (from huggingface-hub>=0.21.2->datasets) (4.12.2)\nRequirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (3.3.2)\nRequirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (2024.7.4)\nRequirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (3.7)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (2.2.2)\nRequirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/site-packages (from pandas->datasets) (2.9.0.post0)\nRequirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/site-packages (from pandas->datasets) (2024.1)\nRequirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/site-packages (from pandas->datasets) (2024.1)\nRequirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)\nInstalling collected packages: xxhash, multiprocess, multidict, frozenlist, async-timeout, aiohappyeyeballs, yarl, aiosignal, aiohttp, datasets\nSuccessfully installed aiohappyeyeballs-2.4.0 aiohttp-3.10.5 aiosignal-1.3.1 async-timeout-4.0.3 datasets-2.21.0 frozenlist-1.4.1 multidict-6.0.5 multiprocess-0.70.16 xxhash-3.5.0 yarl-1.9.4\n\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n\u001b[0m\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m23.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.2\u001b[0m\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n","output_type":"stream"}]},{"cell_type":"code","source":"!pip install ipywidgets","metadata":{"execution":{"iopub.status.busy":"2024-08-21T17:12:25.793563Z","iopub.execute_input":"2024-08-21T17:12:25.793811Z","iopub.status.idle":"2024-08-21T17:12:30.279037Z","shell.execute_reply.started":"2024-08-21T17:12:25.793785Z","shell.execute_reply":"2024-08-21T17:12:30.278259Z"},"trusted":true},"execution_count":3,"outputs":[{"name":"stdout","text":"Collecting ipywidgets\n  Downloading ipywidgets-8.1.3-py3-none-any.whl (139 kB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m139.4/139.4 kB\u001b[0m \u001b[31m3.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n\u001b[?25hCollecting widgetsnbextension~=4.0.11\n  Downloading widgetsnbextension-4.0.11-py3-none-any.whl (2.3 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.3/2.3 MB\u001b[0m \u001b[31m30.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n\u001b[?25hCollecting jupyterlab-widgets~=3.0.11\n  Downloading jupyterlab_widgets-3.0.11-py3-none-any.whl (214 kB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m214.4/214.4 kB\u001b[0m \u001b[31m19.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hRequirement already satisfied: ipython>=6.1.0 in /usr/local/lib/python3.10/site-packages (from ipywidgets) (8.26.0)\nRequirement already satisfied: comm>=0.1.3 in /usr/local/lib/python3.10/site-packages (from ipywidgets) (0.2.2)\nRequirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.10/site-packages (from ipywidgets) (5.14.3)\nRequirement already satisfied: stack-data in /usr/local/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)\nRequirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)\nRequirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.1)\nRequirement already satisfied: decorator in /usr/local/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)\nRequirement already satisfied: typing-extensions>=4.6 in /usr/local/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (4.12.2)\nRequirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)\nRequirement already satisfied: pygments>=2.4.0 in /usr/local/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (2.18.0)\nRequirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /usr/local/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.47)\nRequirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets) (1.2.1)\nRequirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)\nRequirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)\nRequirement already satisfied: wcwidth in /usr/local/lib/python3.10/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)\nRequirement already satisfied: executing>=1.2.0 in /usr/local/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.0.1)\nRequirement already satisfied: pure-eval in /usr/local/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)\nRequirement already satisfied: asttokens>=2.1.0 in /usr/local/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.4.1)\nRequirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/site-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets) (1.16.0)\nInstalling collected packages: widgetsnbextension, jupyterlab-widgets, ipywidgets\nSuccessfully installed ipywidgets-8.1.3 jupyterlab-widgets-3.0.11 widgetsnbextension-4.0.11\n\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n\u001b[0m\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m23.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.2\u001b[0m\n\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n","output_type":"stream"}]},{"cell_type":"code","source":"import os\nfrom transformers import AutoModelForCausalLM, AutoTokenizer\nfrom datasets import load_dataset\nfrom sklearn.feature_extraction.text import TfidfVectorizer\nfrom sklearn.metrics.pairwise import cosine_similarity","metadata":{"execution":{"iopub.status.busy":"2024-08-21T17:12:30.281124Z","iopub.execute_input":"2024-08-21T17:12:30.281422Z","iopub.status.idle":"2024-08-21T17:12:54.872497Z","shell.execute_reply.started":"2024-08-21T17:12:30.281391Z","shell.execute_reply":"2024-08-21T17:12:54.871541Z"},"trusted":true},"execution_count":4,"outputs":[]},{"cell_type":"code","source":"# Set the Hugging Face token\nos.environ[\"HF_TOKEN\"] = \"\"","metadata":{"execution":{"iopub.status.busy":"2024-08-21T17:12:54.873700Z","iopub.execute_input":"2024-08-21T17:12:54.874222Z","iopub.status.idle":"2024-08-21T17:12:54.877993Z","shell.execute_reply.started":"2024-08-21T17:12:54.874188Z","shell.execute_reply":"2024-08-21T17:12:54.877290Z"},"trusted":true},"execution_count":5,"outputs":[]},{"cell_type":"code","source":"# Load the model and tokenizer\nmodel_name = \"meta-llama/Meta-Llama-3.1-8B\"\nmodel = AutoModelForCausalLM.from_pretrained(model_name, use_auth_token=os.getenv(\"HF_TOKEN\"))\ntokenizer = AutoTokenizer.from_pretrained(model_name, use_auth_token=os.getenv(\"HF_TOKEN\"))\n","metadata":{"execution":{"iopub.status.busy":"2024-08-21T17:12:54.878994Z","iopub.execute_input":"2024-08-21T17:12:54.879250Z","iopub.status.idle":"2024-08-21T17:15:09.967909Z","shell.execute_reply.started":"2024-08-21T17:12:54.879226Z","shell.execute_reply":"2024-08-21T17:15:09.966966Z"},"trusted":true},"execution_count":6,"outputs":[{"name":"stderr","text":"/usr/local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:469: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.\n  warnings.warn(\n","output_type":"stream"},{"output_type":"display_data","data":{"text/plain":"config.json:   0%|          | 0.00/826 [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"0a75f125dee94357949cebeb5589e455"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"726639835e9e41a98f1d3884ecfa866f"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Downloading shards:   0%|          | 0/4 [00:00<?, ?it/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"9adb7610e6514da9b2d4e10a84d703a9"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"model-00001-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"e303ee0a6f4a4710ae2febe2394219ea"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"model-00002-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"91edb8bf64c943df8b130d0f211d4333"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"model-00003-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"62bbd942128e4a57bfaf900b863386fd"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"model-00004-of-00004.safetensors:   0%|          | 0.00/1.17G [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"524d35e1c4394a78869cb774fa56892f"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"06a438bf9c2e46969246680b3736710b"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"generation_config.json:   0%|          | 0.00/185 [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"8e9cc081074f40a7b95d38698f1c1ed2"}},"metadata":{}},{"name":"stderr","text":"/usr/local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py:786: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.\n  warnings.warn(\n","output_type":"stream"},{"output_type":"display_data","data":{"text/plain":"tokenizer_config.json:   0%|          | 0.00/50.5k [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"bd03918af668411fabf41f9adf74cd4f"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"2ab73822c4f84344b5621383a1ed309c"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"special_tokens_map.json:   0%|          | 0.00/73.0 [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"42e2f1996b924c8e9314201cde5b2324"}},"metadata":{}}]},{"cell_type":"code","source":"# Assign the eos_token as the pad_token (if needed)\ntokenizer.pad_token = tokenizer.eos_token","metadata":{"execution":{"iopub.status.busy":"2024-08-21T17:15:09.969457Z","iopub.execute_input":"2024-08-21T17:15:09.969974Z","iopub.status.idle":"2024-08-21T17:15:09.974444Z","shell.execute_reply.started":"2024-08-21T17:15:09.969945Z","shell.execute_reply":"2024-08-21T17:15:09.973812Z"},"trusted":true},"execution_count":7,"outputs":[]},{"cell_type":"code","source":"# Load the dataset\ndataset = load_dataset(\"keivalya/MedQuad-MedicalQnADataset\")[\"train\"]","metadata":{"execution":{"iopub.status.busy":"2024-08-21T17:15:09.975422Z","iopub.execute_input":"2024-08-21T17:15:09.975675Z","iopub.status.idle":"2024-08-21T17:15:20.845384Z","shell.execute_reply.started":"2024-08-21T17:15:09.975648Z","shell.execute_reply":"2024-08-21T17:15:20.844655Z"},"trusted":true},"execution_count":8,"outputs":[{"output_type":"display_data","data":{"text/plain":"Downloading readme:   0%|          | 0.00/233 [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"93cfb170f97f4c0a8efac0690eca7532"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Downloading data:   0%|          | 0.00/22.5M [00:00<?, ?B/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"a9d9cee663504b469acf1e9a7468049d"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Generating train split:   0%|          | 0/16407 [00:00<?, ? examples/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"09ac6c095cf149f9b261e5af72f98082"}},"metadata":{}}]},{"cell_type":"code","source":"# Create a TF-IDF vectorizer and fit it on the dataset's 'Answer' column\nvectorizer = TfidfVectorizer().fit(dataset[\"Answer\"])\n\ndef retrieve_documents(question, dataset, vectorizer, top_n=5):\n    # Vectorize the question\n    question_vector = vectorizer.transform([question])\n\n    # Compute similarity between the question and all answers in the dataset\n    similarities = cosine_similarity(question_vector, vectorizer.transform(dataset[\"Answer\"]))\n\n    # Get the indices of the top_n most similar answers\n    top_indices = similarities.argsort()[0][-top_n:]\n    \n    # Convert numpy.int64 indices to regular int\n    top_indices = [int(i) for i in top_indices]\n\n    # Retrieve the corresponding answers\n    retrieved_docs = [dataset[i][\"Answer\"] for i in top_indices]\n    return \" \".join(retrieved_docs)","metadata":{"execution":{"iopub.status.busy":"2024-08-21T17:15:20.846510Z","iopub.execute_input":"2024-08-21T17:15:20.846806Z","iopub.status.idle":"2024-08-21T17:15:23.372315Z","shell.execute_reply.started":"2024-08-21T17:15:20.846777Z","shell.execute_reply":"2024-08-21T17:15:23.371454Z"},"trusted":true},"execution_count":9,"outputs":[]},{"cell_type":"code","source":"def rag_pipeline(question, dataset, vectorizer, model, tokenizer):\n    # Retrieve relevant documents based on the question\n    docs = retrieve_documents(question, dataset, vectorizer)\n\n    # Concatenate the question with the retrieved documents\n    combined_input = question + \" \" + docs\n\n    # Tokenize the combined input\n    inputs = tokenizer(combined_input, return_tensors=\"pt\", padding=True, truncation=True, max_length=256)\n\n    # Generate an answer using the model\n    outputs = model.generate(\n        inputs[\"input_ids\"], \n        attention_mask=inputs[\"attention_mask\"],\n        max_new_tokens=50\n    )\n\n    # Decode and return the generated answer\n    return tokenizer.decode(outputs[0], skip_special_tokens=True)\n","metadata":{"execution":{"iopub.status.busy":"2024-08-21T17:34:23.487658Z","iopub.execute_input":"2024-08-21T17:34:23.488037Z","iopub.status.idle":"2024-08-21T17:34:23.492928Z","shell.execute_reply.started":"2024-08-21T17:34:23.487988Z","shell.execute_reply":"2024-08-21T17:34:23.492325Z"},"trusted":true},"execution_count":18,"outputs":[]},{"cell_type":"code","source":"# Example usage\nquestion = \"Who is at risk for Lymphocytic Choriomeningitis (LCM)?\"\nanswer = rag_pipeline(question, dataset, vectorizer, model, tokenizer)\nprint(\"Answer:\", answer)","metadata":{"execution":{"iopub.status.busy":"2024-08-21T17:35:08.310326Z","iopub.execute_input":"2024-08-21T17:35:08.310690Z","iopub.status.idle":"2024-08-21T17:35:30.484280Z","shell.execute_reply.started":"2024-08-21T17:35:08.310660Z","shell.execute_reply":"2024-08-21T17:35:30.483362Z"},"trusted":true},"execution_count":20,"outputs":[{"name":"stderr","text":"Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.\n","output_type":"stream"},{"name":"stdout","text":"Answer: Who is at risk for Lymphocytic Choriomeningitis (LCM)? Lymphocytic colitis is form of microscopic colitis, a condition that is characterized by inflammation of the colon (large intestines). As the name suggests, microscopic colitis can only be diagnosed by examining a small sample of colon tissue under a microscope. In lymphocytic colitis, specifically, the tissues and lining of the colon are of normal thickness, but an increase in the number of lymphocytes (a type of white blood cell) is observed. Signs and symptoms of the condition may include chronic, watery diarrhea; abdominal pain, cramping, and bloating; weight loss; nausea; dehydration; and/or fecal incontinence. The underlying cause of lymphocytic colitis is currently unknown; however, scientists suspect that autoimmune conditions, medications, infections, genetic factors, and/or bile acid malabsorption may contribute to the development of the condition. Treatment is based on the signs and symptoms present in each person and may include certain medications, dietary modifications, and in rare cases, surgery. Older age can affect the risk of developing chronic lymphocytic leukemia. Anything that increases your risk of getting a disease is called a risk factor. Having a risk factor does not mean that you will get cancer; not having risk factors doesn't mean that you will not get cancer. People with chronic lymphocytic leukemia are more likely to develop other types of cancer. People who have chronic lymphocytic leukemia are more\n","output_type":"stream"}]},{"cell_type":"code","source":"# Example usage\nquestion = \"How to diagnose Parasites - Cysticercosis ?\"\nanswer = rag_pipeline(question, dataset, vectorizer, model, tokenizer)\nprint(\"Answer:\", answer)","metadata":{"execution":{"iopub.status.busy":"2024-08-21T17:35:41.887940Z","iopub.execute_input":"2024-08-21T17:35:41.888283Z","iopub.status.idle":"2024-08-21T17:36:05.614256Z","shell.execute_reply.started":"2024-08-21T17:35:41.888256Z","shell.execute_reply":"2024-08-21T17:36:05.613327Z"},"trusted":true},"execution_count":21,"outputs":[{"name":"stderr","text":"Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.\n","output_type":"stream"},{"name":"stdout","text":"Answer: How to diagnose Parasites - Cysticercosis? Cysticercosis is an infection caused by the larvae of the parasite Taenia solium.  This infection occurs after a person swallows tapeworm eggs. The larvae get into tissues such as muscle and brain, and form cysts there (these are called cysticerci). When cysts are found in the brain, the condition is called neurocysticercosis. Diagnosis of Taenia tapeworm infections is made by examination of stool samples; individuals should also be asked if they have passed tapeworm segments. Stool specimens should be collected on three different days and examined in the lab for Taenia eggs using a microscope. Tapeworm eggs can be detected in the stool 2 to 3 months after the tapeworm infection is established.\n    \nTapeworm eggs of T. solium can also infect humans, causing cysticercosis. It is important to diagnose and treat all tapeworm infections.\n    \nMore on: cysticercosis If you think that you may have cysticercosis, please see your health care provider. Your health care provider will ask you about your symptoms, where you have travelled, and what kinds of foods you eat. The doctor will examine you and may order tests to diagnose the infection. The doctor may ask you to provide a stool sample. The stool sample will be tested for tapeworm eggs. In some cases, the doctor may take a biopsy of the infected tissue\n","output_type":"stream"}]},{"cell_type":"code","source":"","metadata":{},"execution_count":null,"outputs":[]}]}
